New survey builder
may-den/academy-survey-app pull request #2
Opened 2016-12-01 13:46 UTC by rmjjjt

2016-12-01 14:25 UTC, aimeeew requested changes

2016-12-01 14:25 UTC, aimeeew commented on module/Application/view/application/builder/index.phtml
> +<hr>
css instead?

2016-12-01 14:25 UTC, aimeeew commented on module/Application/view/application/builder/index.phtml
> +<hr>
this one too?

2016-12-01 14:25 UTC, aimee-wyld commented on public/js/surveyBuilderForm.js
> +    var addQuestionButton = $('#add-question')
$variable for jQuery selector?

2016-12-01 14:25 UTC, aimee-wyld commented on public/js/surveyBuilderForm.js
> +        } else if($('#input-selector').val() == 'text-input')
could this just be an else?

2016-12-01 14:25 UTC, aimee-wyld commented on public/js/surveyBuilderForm.js
> +    $('#input-selector').change(function()
lots of repetition of this input-selector - could be a variable?

2016-12-01 14:25 UTC, aimee-wyld commented on public/js/surveyBuilderForm.js
> +    $('#question').keyup(function(e)
do you need 'e' here if it's not used?

2016-12-01 14:25 UTC, aimee-wyld commented on public/js/surveyBuilderForm.js
> +    addQuestionButton.click(function(e)
e

2016-12-01 14:25 UTC, aimee-wyld commented on public/js/surveyBuilderForm.js
> +                    options.each(function(key,option)
space in parameters?

2016-12-01 14:25 UTC, aimee-wyld commented on public/js/surveyBuilderForm.js
> +                if(options.length)
would this work as an else if?

2016-12-01 14:25 UTC, aimee-wyld commented on public/js/surveyBuilderForm.js
> +            var newQuestion =   '<div class="new-question ui-state-default">' +
spacing?

2016-12-01 14:25 UTC, aimee-wyld commented on public/js/surveyBuilderForm.js
> +$(function(){
some comments throughout could be useful?

2016-12-01 14:25 UTC, aimee-wyld commented on public/js/surveyBuilderForm.js
> +function  createOption($optionContainer)
extra space?

2016-12-01 14:25 UTC, aimee-wyld commented on public/js/surveyBuilderForm.js
> +    validateNewQuestion($('#question').val(), $('#add-question'), $('#input-selector').val())
these same selectors are used throughout?

2016-12-01 16:28 UTC, ralph-rutter commented on public/js/surveyBuilderForm.js
> +    $('#input-selector').change(function()
Done.

2016-12-01 16:34 UTC, ralph-rutter commented on public/js/surveyBuilderForm.js
> +function  createOption($optionContainer)
It looks weird when the function description is only on one line, but this style of having a blank line between the description and parameter list is consistent across my DocBlocks and seems (after a little googling) to be a style adopted by others.

2016-12-01 16:49 UTC, ralph-rutter commented on public/js/surveyBuilderForm.js
> +        } else if($('#input-selector').val() == 'text-input')
I thought the same initially, as did Mike, but there is a slight distinction: 

The "if" checks if the input selector is being changed from the text type to another type, in which  case the options controller pops up.
The "else if" checks if the new type is text, in which case it removes the options controls. The case where it is being changed from radio to checkbox or vice versa is false in both cases, and hence we neither create nor remove the options controls.

2016-12-01 19:07 UTC, aimee-wyld commented on public/js/surveyBuilderForm.js
> +function  createOption($optionContainer)
Sorry my comment was really unclear but we meant that before the function name 'createOption' it looks like there's more than one space (super picky but we were trying to be really careful!)

2016-12-01 19:08 UTC, aimee-wyld commented on public/js/surveyBuilderForm.js
> +        } else if($('#input-selector').val() == 'text-input')
That makes sense - thanks for explaining :)

2016-12-01 19:38 UTC, ralph-rutter commented on public/js/surveyBuilderForm.js
> +    validateNewQuestion($('#question').val(), $('#add-question'), $('#input-selector').val())
I had a look and could see no reason why they couldn't be variables, so started making the changes. I then remembered a chat I had with Mike yesterday about this and he said this is one of those development compromises: on one hand it's inefficient to keep making jQuery selections, but on the other validateNewQuestion() is called by other, unrelated, functions, so in order to enforce dependency injection the variables would have to be passed into places where it doesn't really make sense to. He concluded that it's better to leave as is. I'll go and undo the changes I started making then! lol

2016-12-01 20:47 UTC, JessI23 commented on public/js/surveyBuilderForm.js
> +    var addQuestionButton = $('#add-question')
fixed

2016-12-01 20:50 UTC, JessI23 commented on public/js/surveyBuilderForm.js
> +    addQuestionButton.click(function(e)
removed

2016-12-01 20:55 UTC, JessI23 commented on public/js/surveyBuilderForm.js
> +                if(options.length)
actually the if is no longer necessary so changed to just an else

2016-12-01 20:56 UTC, JessI23 commented on public/js/surveyBuilderForm.js
> +                    options.each(function(key,option)
done

2016-12-01 21:09 UTC, JessI23 commented on public/js/surveyBuilderForm.js
> +        validateNewQuestion($('#question').val(), addQuestionButton, $type.val())
relying on lexical scope for addQuestionButton?

2016-12-01 21:56 UTC, JessI23 commented on public/js/surveyBuilderForm.js
> +        } else if ($type.val() == 'text-input') { // checking that it's being changed to the text input type
$type - relying on scope? possible to use $(this)?

2016-12-01 22:11 UTC, JessI23 commented on public/js/surveyBuilderForm.js
> +            addOptionsCreator($('#input-container')) // brings up the multiple choice options controls
should you comment a function call? surely the comment on the function should be enough?

2016-12-01 22:17 UTC, JessI23 commented on public/js/surveyBuilderForm.js
> +     * @param STRING question text in question's text box
parameter text does not match parameter names in docblock

2016-12-02 10:01 UTC, ralph-rutter commented on public/js/surveyBuilderForm.js
> +function  createOption($optionContainer)
Oh right, lol. I took a look and double space appears to be gone already.

2016-12-02 10:03 UTC, ralph-rutter commented on public/js/surveyBuilderForm.js
> +            addOptionsCreator($('#input-container')) // brings up the multiple choice options controls
Cheers, I've removed this comment.

2016-12-02 10:21 UTC, ralph-rutter commented on public/js/surveyBuilderForm.js
> + */
change the data type from JQUERYSELECTOR to OBJECT, as it is the selector's return value that we are assigning to the varibable, not the selector itself. jQuery selectors return jQuery objects, which are themselves JS objects.

2017-03-24 18:49 UTC, closed without merging